name: 'Validate OWASP Metadata File'

on:
  push:
    branches: main
    paths:
      - '*.owasp.yaml'

  pull_request:
    paths:
      - '*.owasp.yaml'

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate OWASP Schema File
        uses: abhayymishraa/nest-schema/.github/actions/validate@main
